version: '3.8'

services:
  log-investigator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Frontend
      - "8000:8000"  # Backend
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app/backend
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 