global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Log Investigator Backend
  - job_name: 'log-investigator-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Log Investigator Frontend
  - job_name: 'log-investigator-frontend'
    static_configs:
      - targets: ['frontend:4000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx (if nginx-exporter is added)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']

  # Redis (if redis-exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node Exporter (for host metrics)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.localhost:9323']  # Docker Desktop on macOS
      # - targets: ['localhost:9323']  # Linux Docker
    metrics_path: '/metrics'
    scrape_interval: 30s 